micronaut:
  application:
    name: msProposta
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db_proposta
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

address:
  client:
    url: ${ADDRESS_CLIENT_URL:`https://viacep.com.br/ws`}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    credit-analysis:
      address: ${ADDRESS_CREDIT_ANALYSIS:`localhost:50052`}
      plaintext: true
      max-retry-attempts: 5
