micronaut:
  application:
    name: msProposta
  server:
    port: ${SERVER_PORT_HTTP:8080}

#Data base
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db_proposta
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

#Service Grpc external
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    credit-analysis:
      address: ${ADDRESS_CREDIT_ANALYSIS:`localhost:50052`}
      plaintext: true
      max-retry-attempts: 5
  server:
    health:
      enabled: true
    port: ${SERVER_PORT_GRPC:50051}

#Healthcheck
endpoints:
  all:
    sensitive: false
  health:
    enable: true
    sensitive: false
    details-visible: ANONYMOUS


#Kafka
kafka:
  bootstrap:
    servers: localhost:9092
  embedded:
    enabled: true
    topic:
      - card-create



