micronaut:
  application:
    name: creditAnalysis
  server:
    port: ${SERVER_PORT_HTTP:8082}

#Service GRPC
grpc:
  server:
    port: ${SERVER_PORT:50052}
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    account:
      address: ${ADDRESS_ACCOUNT:`localhost:50053`}
      plaintext: true
      max-retry-attempts: 5

#Healthcheck
endpoints:
  all:
    sensitive: false
  health:
    enable: true
    sensitive: false
    details-visible: ANONYMOUS