micronaut:
  application:
    name: account

#Database
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/db_account
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

#GRPC
grpc:
  server:
    health:
      enabled: true
    port: ${SERVER_PORT_GRPC:50053}


#Kafka
kafka:
  bootstrap:
    servers: localhost:9092
  embedded:
    enabled: true
    topic:
      - card-create

endpoints:
  all:
    enabled: true
    sensitive: false